# Generated by Django 2.0.7 on 2018-08-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(blank=True, to='orders.Pasta'),
        ),
    ]
