# Generated by Django 2.0.7 on 2018-07-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='small',
            field=models.FloatField(),
        ),
    ]
