# Generated by Django 2.0.7 on 2018-07-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180729_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dinnerplates',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dinnerplates',
            name='small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salads',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subs',
            name='small',
            field=models.FloatField(),
        ),
    ]
