# Generated by Django 2.0.7 on 2018-07-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180729_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='large',
            field=models.FloatField(),
        ),
    ]
