# Generated by Django 2.0.7 on 2018-07-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180731_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='small',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
