# Generated by Django 2.0.7 on 2018-07-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180731_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
    ]
