# Generated by Django 2.0.7 on 2018-07-31 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pasta1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pasta1',
        ),
    ]
