# Generated by Django 2.0.7 on 2018-08-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delete_pasta1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cartitem', models.ManyToManyField(blank=True, related_name='cart', to='orders.Pasta')),
            ],
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
