# Generated by Django 2.0.7 on 2018-08-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180802_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_pasta', to='orders.Pasta')),
            ],
        ),
    ]
