# Generated by Django 2.0.7 on 2018-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180802_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cartitems_salads',
            field=models.ManyToManyField(blank=True, related_name='cart1', to='orders.Salads'),
        ),
    ]
